#!/bin/bash

if [[ ! $1 =~ task[1-5] ]]; then
    echo "$1 is not a known task"
    exit 1
fi

if oc get deployment $1 > /dev/null 2> /dev/null; then
    oc get deployment $1 -o yaml | oc replace --force -f -
    exit 0
fi

if oc get pods $1 > /dev/null 2> /dev/null; then
    oc get pod $1 -o yaml | oc replace --force -f -
    exit 0
fi

echo "Not sure what to do with $1"
exit 1
